name: url-shortener

services:
  master-database:
    image: postgres:17.4
    restart: always
    env_file:
      - ${HOME}/.env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_WAL_LEVEL: replica
      POSTGRES_MAX_WAL_SENDERS: 3
      POSTGRES_MAX_REPLICATION_SLOTS: 3
      POSTGRES_LISTEN_ADDRESSES: '*'
      POSTGRES_HOT_STANDBY: 'on'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - master-database-data:/data/pg_data
      - ./database/pg_hba_conf_set_up.sh:/docker-entrypoint-initdb.d/pg_hba_conf_set_up.sh
      - ./database/init_replication_user.sh:/docker-entrypoint-initdb.d/init_replication_user.sh
      - ./database/initialize_db_tables.sql:/docker-entrypoint-initdb.d/initialize_db_tables.sql
    networks:
      - url-shortener


  replica-database:
    image: postgres:17.4
    restart: always
    env_file:
      - ${HOME}/.env
    ports:
      - "${POSTGRES_HOST_PORT_REPLICA}:5432"
    volumes:
      - replica-database-data:/var/lib/postgresql/data
      - ./database/start_replica.sh:/usr/local/bin/start_replica.sh
    command: [ "/usr/local/bin/start_replica.sh" ]
    depends_on:
      - master-database
    networks:
      - url-shortener

  url-shortener-write-service:
    build:
      context: url-shortener-service
      dockerfile: Dockerfile
    container_name: url-shortener-write-service
    restart: always
    depends_on:
      - master-database
      - replica-database
    env_file:
      - ${HOME}/.env
    ports:
      - "${DOCKER_URL_SHORTENER_WRITE_SERVICE_LISTEN_HOST_PORT}:8080"
    volumes:
      - ${HOME}/app/logs/:/app/logs
      - ${HOME}/.env:/root/.env:ro
    networks:
      - url-shortener

  url-shortener-read-service:
    build:
      context: url-shortener-read-service
      dockerfile: Dockerfile
    container_name: url-shortener-read-service
    restart: always
    depends_on:
      - master-database
    env_file:
      - ${HOME}/.env
    ports:
      - "${DOCKER_URL_SHORTENER_READ_SERVICE_LISTEN_HOST_PORT}:8080"
    volumes:
      - ${HOME}/app/logs/:/app/logs
      - ${HOME}/.env:/root/.env:ro
    networks:
      - url-shortener


volumes:
  master-database-data:
  replica-database-data:

networks:
  url-shortener:
    driver: bridge
