name: url-shortener

services:
  master-database:
    image: postgres:17.4
    restart: always
    env_file:
      - ${HOME}/.env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - master-database-data:/data/pg_data

  url-shortener-write-service:
    build:
      context: url-shortener-service
      dockerfile: Dockerfile
    container_name: url-shortener-write-service
    restart: always
    depends_on:
      - master-database
    env_file:
      - ${HOME}/.env
    ports:
      - "${DOCKER_URL_SHORTENER_WRITE_SERVICE_LISTEN_HOST_PORT}:8080"
    volumes:
      - ${HOME}/app/logs/:/app/logs
      - ${HOME}/.env:/root/.env:ro
    
  url-shortener-read-service:
    build:
      context: url-shortener-read-service
      dockerfile: Dockerfile
    container_name: url-shortener-read-service
    restart: always
    depends_on:
      - master-database
    env_file:
      - ${HOME}/.env
    ports:
      - "${DOCKER_URL_SHORTENER_READ_SERVICE_LISTEN_HOST_PORT}:8080"
    volumes:
      - ${HOME}/app/logs/:/app/logs
      - ${HOME}/.env:/root/.env:ro

volumes:
  master-database-data:
